name: Deploy MkDocs Site

on:
  push:
    branches:
      - master # Ensure this matches the branch where you're making changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.3" # Replace with your specific Python version

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material  # Include if using this theme or other plugins

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
